### PR TITLE
Copy assert/enforce guide from internal repo

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
Introduces new folder for coding style and guidelines related information.
Copies one of such document so that it can be linked from tsunami ocean repo.

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
FYI @leandro-lucarella-sociomantic

**Comment by leandro-lucarella-sociomantic** [comment]
I guess after the import it will need an update to talk about `verify()`?

**Comment by leandro-lucarella-sociomantic** [comment]
@dylan-cromwell-sociomantic even when you might not be in the details, it would be good to know your input about if this is the right place or about folder structure and such.

**Comment by mihails-strasuns-sociomantic** [comment]
Yep. I think best to do it in this order:
1) Merge this guide as-is
2) Link it from verify PR and merge it
3) Update the guide with verify info

**Review by leandro-lucarella-sociomantic — APPROVED** [review]
LGTM but I'd wait for @dylan-cromwell-sociomantic input on the repo structure.

**Comment by dylan-cromwell-sociomantic** [comment]
Hey @mihails-strasuns-sociomantic @leandro-lucarella-sociomantic I think this looks really good and definitely see no reason that it can't live here. Showing our human behavior guidelines as well as our tech behavior guidelines is a great, full picture. Awesome work and full clearance to go forward with this! 👍

**Comment by dylan-cromwell-sociomantic** [comment]
@mihails-strasuns-sociomantic perhaps we should update the top level README to reflect the new expansion of content? What do you think?

**Comment by dylan-cromwell-sociomantic** [comment]
@mihails-strasuns-sociomantic I just realized I do have a question: is it preferred for us to use .md or .rst? I am not for or against one or the other (though I am personally more used to .md) but it may be relevant for us to consider a single choice for consistency.

**Comment by mihails-strasuns-sociomantic** [comment]
Our internal docs used to be in rst originally but there is a slow overall move towards md for consistency so if @leandro-lucarella-sociomantic doesn't mind, I am OK converting it.

**Comment by dylan-cromwell-sociomantic** [comment]
@mihails-strasuns-sociomantic understood, thank you for the insight! Sounds like a plan if @leandro-lucarella-sociomantic agrees.

**Comment by leandro-lucarella-sociomantic** [comment]
> Our internal docs used to be in rst originally but there is a slow overall move towards md for consistency so if @leandro-lucarella-sociomantic doesn't mind, I am OK converting it.

Yeah, it was agreed that, since some parts of GitHub don't support reST (like comments, release notes, etc.), the advantages of using reST where we can are not enough to justify using 2 formats, that proved to confuse a lot of people.

Let's go for .md for new documents!

**Comment by dylan-cromwell-sociomantic** [comment]
Great, cheers for the input @leandro-lucarella-sociomantic!

**Pull request merged**
