### PR TITLE
Document usage of ocean.core.Test

### PR DESCRIPTION
**Pull request by gavin-norman-sociomantic**

### CODE REVIEW

**Comment by gavin-norman-sociomantic** [comment]
@mihails-strasuns-sociomantic

**Comment by mihails-strasuns-sociomantic** [comment]
I would add "For all purposes, `test` is simply an `enforce` with pre-defined exception type" statement somewhere in the beginning - to make it clear it is not yet another completely new entity.

**Comment by gavin-norman-sociomantic** [comment]
Updated.

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Comment by mihails-strasuns-sociomantic** [comment]
LGTM

**Review by leandro-lucarella-sociomantic — APPROVED** [review]

**Pull request merged**
