### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by gautam-kotian-sociomantic**

### CODE REVIEW

**Comment by dylan-cromwell-sociomantic** [comment]
@gautam-kotian-sociomantic our current style guide (unless it changed) requestes US English, not UK English, so the change from "behavior" would not be correct. Can you update your PR to remove this?

**Comment by gautam-kotian-sociomantic** [comment]
Ah ok, will update.

**Comment by gautam-kotian-sociomantic** [comment]
Fixed my bad "behaviour".

**Review by leandro-lucarella-sociomantic — APPROVED** [review]

**Comment by leandro-lucarella-sociomantic** [comment]
Thanks!

**Pull request merged**
